## Business Case 

You are working as a Data Engineer for QuickCart, a rapidly growing e-commerce and logistics  platform. 
The company currently faces: 
- Slow dashboard performance 
- Duplicate customer records 
- Delayed reporting 
- Pipeline failures 
- High storage costs 
- Difficulty processing clickstream logs 
- Poor query performance on large datasets
- 
The organization wants to build a scalable modern data platform using: Python, SQL, Pandas, Airflow and modern ETL/ELT architecture.

### DATASETS PROVIDED 

1. **customers.csv** 
- customer_id 
- customer_name 
- email 
- city 
- signup_date 
2. **orders.csv** 
- order_id 
- customer_id 
- product_id 
- order_date 
- quantity 
- unit_price 
- payment_status 
3. **products.csv** 
- product_id 
- product_name 
- category 
- supplier_id 
- cost_price 
- selling_price 
4. **clickstream.csv** 
- event_id 
- customer_id 
- event_type 
- page_url 
- event_timestamp 
- device_type

## Section C - Python + Pandas Engineering

In [1]:
import pandas as pd
import numpy as np

### 1. Read all datasets

In [2]:
customers= pd.read_csv('files\customers.csv')
orders= pd.read_csv('files\orders.csv')
products= pd.read_csv('files\products.csv')
clickstream= pd.read_csv('files\clickstream.csv')

### Inspecting the datasets

In [3]:
customers.head(10)

,customer_id,customer_name,email,city,signup_date
0,1,William Jennings,william.jennings1@example.com,Dublin,2025-01-29
1,2,Diane Newman,diane.newman2@example.com,Manchester,2025-11-06
2,3,Samuel Wright,samuel.wright3@example.com,London,2024-08-12
3,4,Gillian Barnes,gillian.barnes4@example.com,Lisbon,2025-09-15
4,5,Nigel Edwards,nigel.edwards5@example.com,Glasgow,2025-11-23
5,6,Ms Rosemary Wright,ms.rosemary.wright6@example.com,Edinburgh,2026-02-07
6,7,Tracy Harrison,tracy.harrison7@example.com,Edinburgh,2025-03-16
7,8,Gillian Andrews,gillian.andrews8@example.com,Birmingham,2025-03-13
8,9,Janice Glover,janice.glover9@example.com,Lisbon,2026-03-06
9,10,Wayne Gough,wayne.gough10@example.com,Manchester,2025-12-13

In [4]:
orders.head(10)

,order_id,customer_id,product_id,order_date,quantity,unit_price,payment_status
0,1001,21,105,2028-03-29,1,1999.0,Paid
1,1002,71,109,2025-03-04,2,2499.0,Paid
2,1003,86,105,2025-09-12,5,1999.0,Paid
3,1004,42,101,2026-10-14,2,249.0,Pending
4,1005,24,107,2026-04-05,3,799.0,Paid
5,1006,40,106,2027-12-16,2,349.0,Paid
6,1007,54,108,2026-09-10,2,149.0,Paid
7,1008,90,109,2026-08-28,5,2499.0,Paid
8,1009,66,107,2027-06-27,5,799.0,Paid
9,1010,97,103,2025-05-22,5,1299.0,Paid

In [5]:
products.head(10)

,product_id,product_name,category,supplier_id,cost_price,selling_price
0,101,Wireless Mouse,Electronics,5,146.86,249.0
1,102,Bluetooth Speaker,Electronics,1,377.54,599.0
2,103,Office Chair,Furniture,2,726.22,1299.0
3,104,Notebook Pack,Stationery,4,61.65,89.0
4,105,4K Monitor,Electronics,2,1307.08,1999.0
5,106,Desk Lamp,Furniture,5,234.27,349.0
6,107,Mechanical Keyboard,Electronics,5,461.79,799.0
7,108,Water Bottle,Home & Living,4,91.44,149.0
8,109,Standing Desk,Furniture,6,1869.56,2499.0
9,110,Backpack,Accessories,5,358.54,499.0

In [6]:
clickstream.head(10)

,event_id,customer_id,event_type,page_url,event_timestamp,device_type
0,1861,7.0,purchase,/help,2025-02-05 08:29:38,Tablet
1,354,83.0,Page_View,/product/101,2025-07-13 20:51:00,MOBILE
2,1334,97.0,CLICK,/account,03/03/2025 18:50,NaN
3,906,91.0,ADD TO CART,/orders,04/06/2025 06:10,MOBILE
4,1290,25.0,page_view,/orders,2025-01-15 20:47:38,MOBILE
5,1274,13.0,pageview,/account,13/03/2025 20:37,Desktop
6,939,6.0,purchase,/checkout,03/06/2025 21:23,Tablet
7,1732,79.0,Click,/search,2025-04-27T00:54:10Z,tablet
8,66,44.0,Search,/product/105,22/05/2025 05:21,NaN
9,1324,7.0,logout,/cart,16/02/2025 00:45,MOBILE

### Analyzing the raw datasets

In [7]:
print(f"Customers dataset (rows,columns): {customers.shape}")
print(f"Orders dataset (rows,columns): {orders.shape}")
print(f"Products dataset (rows,columns): {products.shape}")
print(f"Clickstream dataset (rows,columns): {clickstream.shape}")

Customers dataset (rows,columns): (100, 5)
Orders dataset (rows,columns): (500, 7)
Products dataset (rows,columns): (10, 6)
Clickstream dataset (rows,columns): (2000, 6)

### 2. Validate schema consistency

In [8]:
print(f"\033[1mCustomers dataset schema:\033[0m\n {customers.dtypes}\n")
print(f"\033[1mOrders dataset schema:\033[0m\n {orders.dtypes}\n")
print(f"\033[1mProducts dataset schema:\033[0m\n {products.dtypes}\n")
print(f"\033[1mClickstream dataset schema:\033[0m\n {clickstream.dtypes}\n")

Customers dataset schema:
 customer_id       int64
customer_name    object
email            object
city             object
signup_date      object
dtype: object

Orders dataset schema:
 order_id            int64
customer_id         int64
product_id          int64
order_date         object
quantity            int64
unit_price        float64
payment_status     object
dtype: object

Products dataset schema:
 product_id         int64
product_name      object
category          object
supplier_id        int64
cost_price       float64
selling_price    float64
dtype: object

Clickstream dataset schema:
 event_id             int64
customer_id        float64
event_type          object
page_url            object
event_timestamp     object
device_type         object
dtype: object

### 3. Detect duplicate customers

In [9]:
customers[customers.duplicated(subset= ['customer_id'], keep= False)]

Empty DataFrame
Columns: [customer_id, customer_name, email, city, signup_date]
Index: []

As we can see there are no duplicate records in the `customers` dataset.

### 4. Identify invalid records.

In [10]:
products['category'].unique()

array(['Electronics', 'Furniture', 'Stationery', 'Home & Living',
       'Accessories'], dtype=object)

In [11]:
customers['city'].unique()

array(['Dublin', 'Manchester', 'London', 'Lisbon', 'Glasgow', 'Edinburgh',
       'Birmingham', 'Warsaw', 'Rome', 'Amsterdam', 'Berlin', 'Madrid',
       'Vienna', 'Brussels', 'Paris'], dtype=object)

In [12]:
orders['payment_status'].unique()

array(['Paid', 'Pending', 'Failed', 'Refunded'], dtype=object)

In [13]:
clickstream['event_type'].unique()

array([' purchase ', 'Page_View', 'CLICK ', 'ADD TO CART', ' page_view',
       'pageview', 'Click', 'Search', 'logout', 'clik', 'purchase',
       'add_to_cart', 'Logout', 'SEARCH', 'Purchase', 'Add_To_Cart',
       'log_out', 'click', 'serach', 'PAGEVIEW', 'PURCHASE', 'page_view',
       'LOG OUT', 'add-to-cart', 'search'], dtype=object)

In [14]:
clickstream['device_type'].unique()

array(['Tablet', 'MOBILE', nan, 'Desktop', 'tablet', 'desktop', 'mobile',
       'Mobile'], dtype=object)

Inconsistent data in clickstream dataset for columns `event_type` and `device_type`

In [15]:
# detecting null values

datasets = {
    "customers": customers,
    "orders": orders,
    "products": products,
    "clickstream": clickstream
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isna().sum())

CUSTOMERS
customer_id      0
customer_name    0
email            0
city             0
signup_date      0
dtype: int64

ORDERS
order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
unit_price        0
payment_status    0
dtype: int64

PRODUCTS
product_id       0
product_name     0
category         0
supplier_id      0
cost_price       0
selling_price    0
dtype: int64

CLICKSTREAM
event_id             0
customer_id         60
event_type           0
page_url            83
event_timestamp      0
device_type        424
dtype: int64

In clickstream dataset there are 60 null customer_id, although this might even suggest that the customer did not register and browsed. There are 83 null page_url and 424 null device_type.

In [16]:
clickstream['event_timestamp'].unique()

array(['2025-02-05 08:29:38', '2025-07-13 20:51:00', '03/03/2025 18:50',
       ..., '2025-03-15 10:20:07', '2025-07-06T01:14:53Z',
       '16/01/2025 16:26'], dtype=object)

The formatting of `event_timestamp` is inconsistent

In [17]:
orders['order_date'].unique()

array(['2028-03-29', '2025-03-04', '2025-09-12', '2026-10-14',
       '2026-04-05', '2027-12-16', '2026-09-10', '2026-08-28',
       '2027-06-27', '2025-05-22', '2025-07-04', '2026-07-14',
       '2027-01-13', '2026-06-02', '2026-02-17', '2027-04-23',
       '2026-07-31', '2026-07-10', '2026-07-11', '2027-12-15',
       '2025-07-31', '2025-11-18', '2026-08-17', '2026-04-26',
       '2028-02-22', '2025-08-23', '2027-10-15', '2027-06-23',
       '2026-04-28', '2026-04-27', '2027-01-12', '2025-08-13',
       '2025-10-24', '2028-01-16', '2026-05-07', '2026-10-31',
       '2026-10-01', '2026-04-29', '2027-03-31', '2026-07-03',
       '2024-12-13', '2027-01-29', '2026-09-22', '2026-09-15',
       '2026-02-11', '2026-12-30', '2027-07-06', '2025-12-25',
       '2025-09-08', '2026-11-08', '2026-05-26', '2025-01-04',
       '2026-04-07', '2027-11-05', '2028-01-18', '2026-10-28',
       '2026-06-23', '2026-05-21', '2025-03-23', '2026-03-08',
       '2028-01-06', '2027-04-17', '2025-05-04', '2027-02-21',
       '2026-06-09', '2027-02-23', '2025-07-26', '2026-05-12',
       '2026-10-05', '2027-05-25', '2026-08-14', '2025-11-22',
       '2025-01-10', '2024-09-26', '2027-08-25', '2025-06-20',
       '2026-11-22', '2024-12-05', '2026-11-14', '2026-06-25',
       '2025-10-29', '2026-07-01', '2027-01-08', '2026-02-08',
       '2026-01-05', '2025-09-04', '2027-09-30', '2026-09-04',
       '2026-01-07', '2026-07-07', '2027-01-26', '2026-03-18',
       '2026-11-11', '2026-12-08', '2026-07-06', '2025-08-11',
       '2025-07-15', '2025-09-05', '2026-05-08', '2028-01-14',
       '2026-03-09', '2025-01-17', '2027-01-15', '2028-03-03',
       '2026-10-19', '2027-12-05', '2027-01-30', '2026-02-14',
       '2026-02-05', '2027-10-14', '2027-03-25', '2026-08-23',
       '2025-08-27', '2026-01-23', '2027-08-13', '2025-09-16',
       '2027-07-27', '2026-05-10', '2027-01-23', '2026-04-12',
       '2026-01-12', '2026-12-24', '2027-10-08', '2027-05-06',
       '2025-07-22', '2027-01-21', '2026-02-09', '2026-03-26',
       '2026-07-09', '2025-06-05', '2027-10-07', '2026-12-19',
       '2025-04-26', '2025-08-01', '2025-06-28', '2026-03-21',
       '2024-10-06', '2027-02-18', '2025-10-25', '2026-07-24',
       '2026-07-18', '2027-03-16', '2026-08-31', '2027-06-13',
       '2027-03-06', '2026-02-03', '2027-08-04', '2026-12-01',
       '2026-12-07', '2027-03-29', '2026-04-04', '2026-03-05',
       '2027-09-07', '2025-06-17', '2027-09-11', '2027-02-28',
       '2025-10-20', '2026-06-12', '2025-10-05', '2026-02-21',
       '2026-06-06', '2025-02-27', '2026-06-21', '2026-01-01',
       '2027-06-08', '2025-12-03', '2026-02-19', '2026-12-14',
       '2025-02-25', '2026-06-11', '2027-04-13', '2025-06-26',
       '2026-03-02', '2026-01-21', '2026-08-29', '2025-05-13',
       '2026-09-12', '2027-11-27', '2025-12-10', '2026-11-19',
       '2027-08-15', '2027-12-24', '2026-09-28', '2025-03-08',
       '2026-11-24', '2027-02-01', '2026-04-23', '2026-10-07',
       '2027-07-23', '2027-02-17', '2025-11-03', '2027-11-19',
       '2026-06-01', '2028-01-25', '2027-10-01', '2027-08-11',
       '2024-09-30', '2026-08-02', '2026-08-22', '2027-04-06',
       '2024-11-09', '2027-09-21', '2027-10-09', '2025-06-13',
       '2026-08-04', '2027-01-27', '2025-11-30', '2027-07-18',
       '2026-07-08', '2027-04-22', '2026-11-27', '2026-04-19',
       '2026-12-11', '2025-11-23', '2027-04-15', '2026-10-26',
       '2027-11-07', '2025-11-15', '2025-04-23', '2027-03-01',
       '2026-08-27', '2025-09-18', '2025-07-09', '2027-05-29',
       '2026-03-06', '2026-11-18', '2028-02-06', '2025-03-05',
       '2026-03-16', '2027-03-27', '2026-07-20', '2025-07-08',
       '2026-03-24', '2026-09-09', '2027-05-17', '2027-11-17',
       '2027-05-03', '2028-01-03', '2026-04-01', '2026-04-03',
       '2027-07-31', '2028-04-14', '2025-12-13', '2026-09-13',
       '2025-09-22', '2026-05-13', '2027-06-30', '2025-09-23',
       '2026-03-25', '2027-11-09', '2027-09-25', '2026-05-19',
       '2025-01-12', '2025-02-07', '2027-04-02', '2025-04-20',
       '2025-11-21', '2027-06-15', '2026-06-27', '2026-09-08',
       '2027-08-01', '2026-02-12', '2027-01-10', '2027-05-01',
       '2026-03-01', '2025-08-12', '2026-08-13', '2026-08-10',
       '2026-02-10', '2025-09-17', '2026-04-06', '2025-05-31',
       '2026-10-21', '2026-07-25', '2026-12-04', '2027-05-10',
       '2026-12-16', '2025-09-02', '2026-08-11', '2028-01-24',
       '2025-04-16', '2027-06-19', '2026-06-10', '2025-01-15',
       '2026-07-23', '2026-04-20', '2025-08-09', '2026-05-22',
       '2026-03-14', '2024-10-15', '2026-01-22', '2025-12-07',
       '2027-08-29', '2025-07-03', '2027-11-16', '2027-02-04',
       '2026-02-01', '2026-03-31', '2028-03-26', '2026-06-05',
       '2026-06-22', '2027-12-11', '2026-04-17', '2027-09-05',
       '2025-02-28', '2026-04-18', '2026-06-13', '2025-12-15',
       '2026-09-26', '2026-01-26', '2025-11-20', '2024-12-29',
       '2026-03-19', '2026-03-04', '2026-10-13', '2028-01-23',
       '2027-12-09', '2027-01-03', '2028-02-01', '2026-11-04',
       '2026-05-03', '2026-10-03', '2026-10-02', '2025-04-05',
       '2028-02-08', '2027-03-19', '2026-03-20', '2025-09-15',
       '2025-03-11', '2026-06-04', '2028-01-07', '2026-06-24',
       '2026-03-23', '2025-06-25', '2025-04-11', '2026-11-26',
       '2026-02-02', '2025-11-04', '2026-05-16', '2026-03-29',
       '2026-09-16', '2026-10-10', '2027-09-02', '2026-05-06',
       '2026-01-18', '2027-03-11', '2025-10-09', '2027-03-08',
       '2026-10-16', '2027-08-09', '2025-06-24', '2027-02-25',
       '2025-12-22', '2025-02-08', '2025-12-09', '2026-10-08',
       '2026-09-11', '2026-01-24', '2027-04-10', '2026-09-02',
       '2025-06-06', '2027-10-12', '2026-11-28', '2026-09-05',
       '2027-03-10', '2026-05-02', '2026-10-17', '2027-02-03',
       '2026-08-30', '2026-11-02', '2025-12-17', '2026-05-11',
       '2026-03-28', '2026-05-28', '2027-10-03', '2025-10-10',
       '2027-10-25', '2027-07-17', '2027-10-06', '2026-02-28',
       '2026-01-02', '2024-11-05', '2026-12-02', '2027-12-26',
       '2027-04-21', '2027-08-14', '2026-12-03', '2026-03-22',
       '2027-07-16', '2026-08-05', '2026-11-30', '2025-04-02',
       '2026-05-25', '2025-06-30', '2026-10-15', '2026-05-27',
       '2025-11-10', '2026-01-14', '2025-07-17', '2027-05-11'],
      dtype=object)

In [18]:
# checking if any rows in the orders dataset quantity <= 0 or unit_price < 0
orders[(orders['quantity'] <= 0) | (orders['unit_price'] < 0)]

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, payment_status]
Index: []

So, there are no invalid quantity or unit_price in the orders dataset.

In [19]:
# checking if the cp and sp in the products table are lesser than 0:
products[(products['cost_price']< 0) | products['selling_price']< 0]

Empty DataFrame
Columns: [product_id, product_name, category, supplier_id, cost_price, selling_price]
Index: []

No invalid rows for products as well.

In [20]:
# checking if there are any customers in the orders table that are not present in the customers table:
orders[~orders['customer_id'].isin(customers['customer_id'])]

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, payment_status]
Index: []

In [21]:
# checking if there are any invalid product_id in the orders table that is not present in the products table:
orders[~orders['product_id'].isin(products['product_id'])]

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, payment_status]
Index: []

So the references in the `orders` table are all valid.

### Q2. Data Cleaning & Transformation 

#### 1. Standardize city names. (if any)

In [22]:
# Going forward we will make changes in the copied datasets rather than in the raw files:

customer_df= customers.copy()
order_df= orders.copy()
product_df= products.copy()
clickstream_df= clickstream.copy()

In [23]:
customer_df['city'].unique()

array(['Dublin', 'Manchester', 'London', 'Lisbon', 'Glasgow', 'Edinburgh',
       'Birmingham', 'Warsaw', 'Rome', 'Amsterdam', 'Berlin', 'Madrid',
       'Vienna', 'Brussels', 'Paris'], dtype=object)

Already established that there are no inconsistencies in the `city` names.

#### Convert timestamps correctly.  (if any)

In [24]:
clickstream_df['event_timestamp'].dtypes  # the datatpe is an object

dtype('O')

In [25]:
clickstream_df['event_timestamp'].head(12)

0      2025-02-05 08:29:38
1      2025-07-13 20:51:00
2         03/03/2025 18:50
3         04/06/2025 06:10
4      2025-01-15 20:47:38
5         13/03/2025 20:37
6         03/06/2025 21:23
7     2025-04-27T00:54:10Z
8         22/05/2025 05:21
9         16/02/2025 00:45
10    2025-04-12T10:18:47Z
11     2025-01-01 21:16:56
Name: event_timestamp, dtype: object

In [26]:
clickstream_df['event_timestamp']= pd.to_datetime(
    clickstream_df['event_timestamp'],
    format= 'mixed',
    dayfirst= True,
    utc= True,
    errors= 'coerce'
)

clickstream_df.head(12)

,event_id,customer_id,event_type,page_url,event_timestamp,device_type
0,1861,7.0,purchase,/help,2025-02-05 08:29:38+00:00,Tablet
1,354,83.0,Page_View,/product/101,2025-07-13 20:51:00+00:00,MOBILE
2,1334,97.0,CLICK,/account,2025-03-03 18:50:00+00:00,NaN
3,906,91.0,ADD TO CART,/orders,2025-06-04 06:10:00+00:00,MOBILE
4,1290,25.0,page_view,/orders,2025-01-15 20:47:38+00:00,MOBILE
5,1274,13.0,pageview,/account,2025-03-13 20:37:00+00:00,Desktop
6,939,6.0,purchase,/checkout,2025-06-03 21:23:00+00:00,Tablet
7,1732,79.0,Click,/search,2025-04-27 00:54:10+00:00,tablet
8,66,44.0,Search,/product/105,2025-05-22 05:21:00+00:00,NaN
9,1324,7.0,logout,/cart,2025-02-16 00:45:00+00:00,MOBILE
10,57,78.0,clik,/checkout,2025-04-12 10:18:47+00:00,NaN
11,1293,6.0,purchase,/home,2025-01-01 21:16:56+00:00,tablet

In [27]:
# converting datatype for order_date in order_df dataset:
order_df['order_date']= pd.to_datetime(order_df['order_date'])
order_df.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,payment_status
0,1001,21,105,2028-03-29,1,1999.0,Paid
1,1002,71,109,2025-03-04,2,2499.0,Paid
2,1003,86,105,2025-09-12,5,1999.0,Paid
3,1004,42,101,2026-10-14,2,249.0,Pending
4,1005,24,107,2026-04-05,3,799.0,Paid

#### 3. Handle missing values.  (if any)

Based on the missing value analysis the `customer_id` in clickstream had null values, but as can be seen from the above table the formatting is incorrect as well.

In [28]:
clickstream_df.isna().sum()

event_id             0
customer_id         60
event_type           0
page_url            83
event_timestamp      0
device_type        424
dtype: int64

In [29]:
clickstream_df.dtypes

event_id                         int64
customer_id                    float64
event_type                      object
page_url                        object
event_timestamp    datetime64[ns, UTC]
device_type                     object
dtype: object

In [30]:
clickstream_df.fillna({'customer_id':0}, inplace= True)

In [31]:
clickstream_df.isna().sum()

event_id             0
customer_id          0
event_type           0
page_url            83
event_timestamp      0
device_type        424
dtype: int64

In [32]:
clickstream_df['customer_id']= clickstream_df['customer_id'].astype('int64')

In [33]:
clickstream_df.dtypes

event_id                         int64
customer_id                      int64
event_type                      object
page_url                        object
event_timestamp    datetime64[ns, UTC]
device_type                     object
dtype: object

#### 4. Remove corrupted rows

In [34]:
clickstream_df['event_type'].unique()

array([' purchase ', 'Page_View', 'CLICK ', 'ADD TO CART', ' page_view',
       'pageview', 'Click', 'Search', 'logout', 'clik', 'purchase',
       'add_to_cart', 'Logout', 'SEARCH', 'Purchase', 'Add_To_Cart',
       'log_out', 'click', 'serach', 'PAGEVIEW', 'PURCHASE', 'page_view',
       'LOG OUT', 'add-to-cart', 'search'], dtype=object)

In [35]:
clickstream_df['device_type'].unique()

array(['Tablet', 'MOBILE', nan, 'Desktop', 'tablet', 'desktop', 'mobile',
       'Mobile'], dtype=object)

In [36]:
clickstream_df['event_type'] = (
    clickstream_df['event_type']
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('-', '_', regex=False)
)

In [37]:
clickstream_df['event_type'].unique()

array(['purchase', 'page_view', 'click', 'add_to_cart', 'pageview',
       'search', 'logout', 'clik', 'log_out', 'serach'], dtype=object)

In [38]:
clickstream_df['event_type']= clickstream_df['event_type'].replace(to_replace=['log_out'], value= 'logout')
clickstream_df['event_type']= clickstream_df['event_type'].replace(to_replace=['pageview'], value= 'page_view')
clickstream_df['event_type']= clickstream_df['event_type'].replace(to_replace=['serach'], value= 'search')
clickstream_df['event_type']= clickstream_df['event_type'].replace(to_replace=['clik'], value= 'click')

In [39]:
clickstream_df['event_type'].unique()

array(['purchase', 'page_view', 'click', 'add_to_cart', 'search',
       'logout'], dtype=object)

In [40]:
clickstream_df['device_type']= clickstream_df['device_type'].replace(to_replace= np.nan, value= 'Unknown')

In [41]:
clickstream_df['device_type'].unique()

array(['Tablet', 'MOBILE', 'Unknown', 'Desktop', 'tablet', 'desktop',
       'mobile', 'Mobile'], dtype=object)

In [42]:
clickstream_df['device_type']= (clickstream_df['device_type']
                               .str.strip()
                               .str.lower())

In [43]:
clickstream_df['device_type'].unique()

array(['tablet', 'mobile', 'unknown', 'desktop'], dtype=object)

In [44]:
datasets = {
    "customers": customer_df,
    "orders": order_df,
    "products": product_df,
    "clickstream": clickstream_df
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isna().sum())

CUSTOMERS
customer_id      0
customer_name    0
email            0
city             0
signup_date      0
dtype: int64

ORDERS
order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
unit_price        0
payment_status    0
dtype: int64

PRODUCTS
product_id       0
product_name     0
category         0
supplier_id      0
cost_price       0
selling_price    0
dtype: int64

CLICKSTREAM
event_id            0
customer_id         0
event_type          0
page_url           83
event_timestamp     0
device_type         0
dtype: int64

In [45]:
# removing the null values from the clickstream for `page_url`:
clickstream_df.dropna(
    subset=["page_url"],
    inplace=True
)

In [46]:
clickstream_df.isna().sum()

event_id           0
customer_id        0
event_type         0
page_url           0
event_timestamp    0
device_type        0
dtype: int64

#### Invalid rows

In [47]:
clickstream_df.loc[~clickstream_df['customer_id'].isin(customer_df['customer_id'])].shape

(58, 6)

There are 58 customers with customer_id `not in` customers table.

In [48]:
## get the clean subset of data for clickstream:
clickstream_df= clickstream_df.loc[clickstream_df['customer_id'].isin(customer_df['customer_id'])]
clickstream_df.shape

(1859, 6)

In [49]:
clickstream_df.head()

,event_id,customer_id,event_type,page_url,event_timestamp,device_type
0,1861,7,purchase,/help,2025-02-05 08:29:38+00:00,tablet
1,354,83,page_view,/product/101,2025-07-13 20:51:00+00:00,mobile
2,1334,97,click,/account,2025-03-03 18:50:00+00:00,unknown
3,906,91,add_to_cart,/orders,2025-06-04 06:10:00+00:00,mobile
4,1290,25,page_view,/orders,2025-01-15 20:47:38+00:00,mobile

In [50]:
# 1. Check duplicate event IDs within Pandas
print(
    "Duplicate event IDs:",
    clickstream_df['event_id'].duplicated().sum()
)

Duplicate event IDs: 31

In [51]:
# 2. Check event rows:
conflicting_events= clickstream_df.loc[clickstream_df.duplicated(subset='event_id', keep= False)].sort_values('event_id')
display(conflicting_events)

,event_id,customer_id,event_type,page_url,event_timestamp,device_type
1733,2,93,search,/help,2025-06-17 18:36:14+00:00,mobile
1010,2,54,search,/account,2025-06-06 15:55:54+00:00,mobile
289,2,81,click,/cart,2025-04-09 16:37:19+00:00,mobile
1213,10,86,click,/home,2025-03-26 22:30:06+00:00,mobile
825,10,21,purchase,/product/105,2025-03-15 10:18:41+00:00,mobile
...,...,...,...,...,...,...
1726,1427,90,page_view,/home,2025-04-14 13:27:00+00:00,tablet
1281,1471,62,logout,/product/105,2025-02-14 18:38:00+00:00,unknown
357,1471,89,logout,/products,2025-02-10 08:23:49+00:00,unknown
316,1551,99,click,/orders,2025-06-29 19:54:13+00:00,unknown
1993,1551,16,click,/home,2025-05-17 04:54:00+00:00,desktop

In [52]:
rejected_clickstream= conflicting_events.copy()
valid_clickstream= clickstream_df[~clickstream_df.duplicated(subset='event_id', keep=False)]

In [53]:
print("Rows to investigate:", len(rejected_clickstream))
print("Rows with unique event IDs:", len(valid_clickstream))

Rows to investigate: 61
Rows with unique event IDs: 1798

Proceeding with the 1798 rows which are valid ones with no corrupted event_ids.

### Q3. Clickstream Analytics 

#### Using clickstream data: 

**1. Find the most visited pages.**

In [54]:
valid_clickstream.groupby('page_url')['customer_id'].count().reset_index(name= 'most_visited_pages_count').sort_values(by= 'most_visited_pages_count', ascending= False)

       page_url  most_visited_pages_count
8     /products                       194
9       /search                       191
4         /home                       190
7  /product/105                       189
0      /account                       188
6  /product/101                       180
5       /orders                       179
1         /cart                       167
2     /checkout                       167
3         /help                       153

#### 2. Calculate session counts


Session count is a record of the number of times a user visits your website within a given timeframe, such as day, week, or month. A cookie on the visitor’s browser is used to track the user’s activity between the time they enter your domain and the time they leave.

Sessions create a record of all the interactions each visitor has on your website, including all the pages they view and the engagements they make with events, calls-to-action, forms, etc.


Assumption: 

- Every customer's first event starts a new session. Any later event after more than 30 minutes of inactivity starts another.
- NaT for a new session of a new customer when calculating the time difference, since no previous records to compare it with.

In [55]:
session_df= valid_clickstream[['customer_id', 'event_timestamp']]
session_df.head(12)

    customer_id           event_timestamp
0             7 2025-02-05 08:29:38+00:00
1            83 2025-07-13 20:51:00+00:00
2            97 2025-03-03 18:50:00+00:00
3            91 2025-06-04 06:10:00+00:00
4            25 2025-01-15 20:47:38+00:00
5            13 2025-03-13 20:37:00+00:00
6             6 2025-06-03 21:23:00+00:00
7            79 2025-04-27 00:54:10+00:00
9             7 2025-02-16 00:45:00+00:00
10           78 2025-04-12 10:18:47+00:00
11            6 2025-01-01 21:16:56+00:00
12           36 2025-06-12 00:20:22+00:00

In [56]:
session_df= session_df.sort_values(['customer_id', 'event_timestamp'])

In [57]:
session_df['time_diff'] = (
    session_df.groupby('customer_id')['event_timestamp']
    .diff()
)

session_df

      customer_id           event_timestamp        time_diff
603             1 2025-01-01 13:03:00+00:00              NaT
417             1 2025-01-23 05:27:28+00:00 21 days 16:24:28
809             1 2025-01-27 15:01:53+00:00  4 days 09:34:25
255             1 2025-01-31 07:48:40+00:00  3 days 16:46:47
225             1 2025-02-11 10:14:04+00:00 11 days 02:25:24
...           ...                       ...              ...
1360          100 2025-03-10 01:59:00+00:00 10 days 02:01:00
1110          100 2025-04-04 19:15:20+00:00 25 days 17:16:20
375           100 2025-04-21 12:12:00+00:00 16 days 16:56:40
1966          100 2025-06-14 13:40:09+00:00 54 days 01:28:09
1551          100 2025-07-05 01:18:00+00:00 20 days 11:37:51

[1798 rows x 3 columns]

In [58]:
session_df['new_session'] = (
    session_df['time_diff'].isna()
    | (session_df['time_diff'] > pd.Timedelta(minutes=30))
)

session_df

      customer_id           event_timestamp        time_diff  new_session
603             1 2025-01-01 13:03:00+00:00              NaT         True
417             1 2025-01-23 05:27:28+00:00 21 days 16:24:28         True
809             1 2025-01-27 15:01:53+00:00  4 days 09:34:25         True
255             1 2025-01-31 07:48:40+00:00  3 days 16:46:47         True
225             1 2025-02-11 10:14:04+00:00 11 days 02:25:24         True
...           ...                       ...              ...          ...
1360          100 2025-03-10 01:59:00+00:00 10 days 02:01:00         True
1110          100 2025-04-04 19:15:20+00:00 25 days 17:16:20         True
375           100 2025-04-21 12:12:00+00:00 16 days 16:56:40         True
1966          100 2025-06-14 13:40:09+00:00 54 days 01:28:09         True
1551          100 2025-07-05 01:18:00+00:00 20 days 11:37:51         True

[1798 rows x 4 columns]

In [59]:
session_df['session_number'] = (
    session_df.groupby('customer_id')['new_session']
    .cumsum()
)

session_df.head(20)

,customer_id,event_timestamp,time_diff,new_session,session_number
603,1,2025-01-01 13:03:00+00:00,NaT,True,1
417,1,2025-01-23 05:27:28+00:00,21 days 16:24:28,True,2
809,1,2025-01-27 15:01:53+00:00,4 days 09:34:25,True,3
255,1,2025-01-31 07:48:40+00:00,3 days 16:46:47,True,4
225,1,2025-02-11 10:14:04+00:00,11 days 02:25:24,True,5
537,1,2025-02-12 15:55:00+00:00,1 days 05:40:56,True,6
843,1,2025-02-15 16:46:00+00:00,3 days 00:51:00,True,7
1564,1,2025-02-17 07:54:00+00:00,1 days 15:08:00,True,8
1034,1,2025-03-13 19:06:27+00:00,24 days 11:12:27,True,9
102,1,2025-03-15 13:11:31+00:00,1 days 18:05:04,True,10
663,1,2025-03-26 12:36:00+00:00,10 days 23:24:29,True,11
1469,1,2025-03-28 19:27:00+00:00,2 days 06:51:00,True,12
138,1,2025-03-31 06:06:10+00:00,2 days 10:39:10,True,13
647,1,2025-04-14 21:47:38+00:00,14 days 15:41:28,True,14
1897,1,2025-04-20 04:16:54+00:00,5 days 06:29:16,True,15
906,1,2025-04-21 18:21:30+00:00,1 days 14:04:36,True,16
1675,1,2025-05-03 21:58:35+00:00,12 days 03:37:05,True,17
1424,1,2025-06-02 16:35:49+00:00,29 days 18:37:14,True,18
1154,1,2025-06-07 05:42:49+00:00,4 days 13:07:00,True,19
782,2,2025-02-02 20:32:00+00:00,NaT,True,1

In [60]:
total_sessions = session_df['new_session'].sum()

print("Total estimated sessions:", total_sessions)

Total estimated sessions: 1793

In [61]:
session_df.groupby('customer_id')['session_number'].sum().reset_index(name= 'total_sessions').sort_values(by= 'total_sessions', ascending= False)

    customer_id  total_sessions
84           85             435
5             6             378
66           67             378
15           16             351
52           53             351
..          ...             ...
24           25              66
70           71              66
42           43              66
6             7              62
4             5              55

[100 rows x 2 columns]

Most of the unregistered customers have browsed through the website. Other than that `customer_id`: `85, 67, 6`are the most active users

#### 3. Find mobile vs desktop traffic percentage.

In [62]:
total_events= valid_clickstream['device_type'].shape[0]
mobile_users= round(((valid_clickstream[valid_clickstream['device_type']=='mobile'].shape[0])/total_events)*100, 2)
desktop_user= round(((valid_clickstream[valid_clickstream['device_type']=='desktop'].shape[0])/total_events)*100, 2)

print(f"Mobile users traffic percentage: {mobile_users}%\nDesktop users traffic percentage: {desktop_user}%")

Mobile users traffic percentage: 33.59%
Desktop users traffic percentage: 22.36%

#### Inspecting the data Schema for the final dataframe:

In [63]:
print(f"\033[1mCustomers dataset schema:\033[0m\n{customer_df.dtypes}\n")
print(f"\033[1mOrders dataset schema:\033[0m\n{order_df.dtypes}\n")
print(f"\033[1mProducts dataset schema:\033[0m\n{product_df.dtypes}\n")
print(f"\033[1mClickstream dataset schema:\033[0m\n{valid_clickstream.dtypes}\n")

Customers dataset schema:
customer_id       int64
customer_name    object
email            object
city             object
signup_date      object
dtype: object

Orders dataset schema:
order_id                   int64
customer_id                int64
product_id                 int64
order_date        datetime64[ns]
quantity                   int64
unit_price               float64
payment_status            object
dtype: object

Products dataset schema:
product_id         int64
product_name      object
category          object
supplier_id        int64
cost_price       float64
selling_price    float64
dtype: object

Clickstream dataset schema:
event_id                         int64
customer_id                      int64
event_type                      object
page_url                        object
event_timestamp    datetime64[ns, UTC]
device_type                     object
dtype: object

In [64]:
#pip install sqlalchemy pymysql

### Storage

In [65]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv(".env")

url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password=os.environ["MYSQL_PASSWORD"],
    host="localhost",
    port=3306,
    database="quickcart_db"
)

engine = create_engine(url)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [66]:
# deleting rows if exist any:

from sqlalchemy import text

with engine.begin() as conn:

    # Delete child tables first
    conn.execute(text("DELETE FROM clickstream"))
    conn.execute(text("DELETE FROM orders"))

    # Delete parent tables
    conn.execute(text("DELETE FROM products"))
    conn.execute(text("DELETE FROM customers"))

print("Existing QuickCart records cleared!")

Existing QuickCart records cleared!

In [67]:
customer_df.to_sql(
    name="customers",
    con=engine,
    if_exists="append",
    index=False
)

100

In [68]:
product_df.to_sql(
    name="products",
    con=engine,
    if_exists="append",
    index=False
)

10

In [69]:
order_df.to_sql(
    name="orders",
    con=engine,
    if_exists="append",
    index=False
)

500

In [70]:
valid_clickstream.to_sql(
    name="clickstream",
    con=engine,
    if_exists="append",
    index=False
)

1798

In [71]:
customer_df.shape

(100, 5)

In [72]:
order_df.shape

(500, 7)

In [73]:
product_df.shape

(10, 6)

In [74]:
valid_clickstream.shape

(1798, 6)

In [75]:
engine.dispose()